CREATE DATABASE AD_SISTEMAS;
USE AD_SISTEMAS;


CREATE TABLE Turista (
    Id_Turista INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    A_Paterno VARCHAR(50) NOT NULL,
    A_Materno VARCHAR(50) NOT NULL,
    Correo VARCHAR(50) NOT NULL, 
    Telefono VARCHAR(50) NOT NULL,
    Usuario VARCHAR(50) NOT NULL,
    pass VARCHAR(60) NOT NULL,
    Foto VARCHAR(255),
    Estado CHAR,
    Codigo VARCHAR(100)
);

CREATE TABLE Preferencias(
	Id_Preferencia INT AUTO_INCREMENT PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Id_Turista INT NOT NULL
);
ALTER TABLE Preferencias ADD FOREIGN KEY (Id_Turista) references Turista(Id_Turista)
ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE Itinerario(
	Id_Itinerario INT AUTO_INCREMENT PRIMARY KEY,
	Id_Lugar VARCHAR(50) NOT NULL,
	Fecha_Itinerario VARCHAR(50) NOT NULL,
	Hora_Itinerario VARCHAR(50) NOT NULL,
    Latitud VARCHAR(50) NOT NULL,
    Longitud VARCHAR(50) NOT NULL,
	Id_Turista INT NOT NULL
);
ALTER TABLE Itinerario ADD FOREIGN KEY (Id_Turista) references Turista(Id_Turista) 
ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE Favoritos(
	Id_Favoritos INT AUTO_INCREMENT PRIMARY KEY,
	Id_Lugar VARCHAR(50) NOT NULL,
	Id_Turista INT NOT NULL
);
ALTER TABLE Favoritos ADD FOREIGN KEY (Id_Turista) references Turista(Id_Turista) 
ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE Lugar(
	Id_Lugar INT AUTO_INCREMENT PRIMARY KEY,
    Id_google VARCHAR(50) NOT NULL,
	Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE Historial_busqueda(
	Id_Historial INT AUTO_INCREMENT PRIMARY KEY,
	Id_google VARCHAR(50) NOT NULL,
    Fecha VARCHAR(20),
    Hora VARCHAR(20),
    Id_Turista INT NOT NULL
);
ALTER TABLE Historial_busqueda ADD FOREIGN KEY (Id_Turista) references Turista(Id_Turista) 
ON DELETE CASCADE ON UPDATE CASCADE;
